export const UPDATE_LOADER_STATUS = 'UPDATE_LOADER_STATUS';

export const UPDATE_GENDER_STATUS = 'UPDATE_GENDER_STATUS';

export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

export const UPDATE_PDP_ITEM = 'UPDATE_PDP_ITEM';
