export const REPLACE_ORDER_ITEMS = 'REPLACE_ORDER_ITEMS';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';

export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';
export const SYNC_LOCAL_STORAGE_ORDER = 'SYNC_LOCAL_STORAGE_ORDER';
